#!/usr/bin/env node
"use strict";

const http = require("http");

const PORT = process.env.PORT || 3000;

const requestHandler = (req, res) => {
  res.writeHead(200, { "Content-Type": "text/plain; charset=utf-8" });
  res.end("Server-side fold handler\n");
};

const server = http.createServer(requestHandler);

server.listen(PORT, () => {
  console.log(`Fold server listening on port ${PORT}`);
});
